spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vivtoum/config-repo-demo/
          search-paths: config


server:
  port: 1201

################## 配置文件加密配置
encrypt:
  key: vivtoum
  ################## 非对性加密配置
  key-store:
    location: classpath:/config-server.keystore
    alias: config-server
    password: 123456
    secret: 123456

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://192.168.200.128:1001/eureka/,http://192.168.200.128:1002/eureka/,http://192.168.200.128:1003/eureka/
    registry-fetch-interval-seconds: 10

