spring:
  application:
    name: config-server-git
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vivtoum/config-repo-demo/
          search-paths: config/${spring.profiles.active}/
          default-label: ${spring.profiles.active}   #解决监控down
server:
  port: 1201
---
###### 宿舍虚拟机

################## 配置文件加密配置
encrypt:
  key: vivtoum
  ################## 非对性加密配置
  key-store:
    location: classpath:/config-server.keystore
    alias: config-server
    password: 123456
    secret: 123456

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://192.168.200.128:1001/eureka/,http://192.168.200.128:1002/eureka/,http://192.168.200.128:1003/eureka/
    registry-fetch-interval-seconds: 10
spring:
  profiles: dev


---
###### 小米手提虚拟机

################## 配置文件加密配置
encrypt:
  key: vivtoum
  ################## 非对性加密配置
  key-store:
    location: classpath:/config-server.keystore
    alias: config-server
    password: 123456
    secret: 123456

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://192.168.200.128:1001/eureka/,http://192.168.200.128:1002/eureka/,http://192.168.200.128:1003/eureka/
    registry-fetch-interval-seconds: 10
spring:
  profiles: mi

---
###### 阿里云服务器

################## 配置文件加密配置
encrypt:
  key: vivtoum
  ################## 非对性加密配置
  key-store:
    location: classpath:/config-server.keystore
    alias: config-server
    password: 123456
    secret: 123456

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://39.104.107.186:1001/eureka/,http://39.104.107.186:1002/eureka/,http://39.104.107.186:1003/eureka/
    registry-fetch-interval-seconds: 10
spring:
  profiles: prod
---
###### idea自身服务，修改hosts模拟集群

################## 配置文件加密配置
encrypt:
  key: vivtoum
  ################## 非对性加密配置
  key-store:
    location: classpath:/config-server.keystore
    alias: config-server
    password: 123456
    secret: 123456

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    service-url:
      defaultZone: http://svc1:1001/eureka/,http://svc2:1002/eureka/,http://svc3:1003/eureka/
    registry-fetch-interval-seconds: 10
spring:
  profiles: local