######定义 eureka 集群的端口，和地址名######
svc:
  port1: 1001
  port2: 1002
  port3: 1003
  hostname: localhost
###### svc1 ######
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${svc.hostname}:${svc.port2}/eureka/,http://${svc.hostname}:${svc.port3}/eureka/
spring:
  application:
    name: eureka-service
  profiles: svc1
server:
  port: 1001
---
###### svc2 ######
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${svc.hostname}:${svc.port1}/eureka/,http://${svc.hostname}:${svc.port3}/eureka/
spring:
  application:
    name: eureka-service
  profiles: svc2
server:
  port: 1001
---
###### svc3 ######
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${svc.hostname}:${svc.port2}/eureka/,http://${svc.hostname}:${svc.port1}/eureka/
spring:
  application:
    name: eureka-service
server:
  port: 1001